name: "Change PR description"
description: "Changes the description of a Pull Request"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  pr-number:
    description: "Pull Request Number"
    required: true
  openai-token:
    description: "OpenAI Token"
    required: true
  pull-request-template:
    description: "Pull Request Template"
    required: false
  trigger-word:
    description: "Trigger for the action, (auto, or any trigger word in PR description)"
    required: false
  openai-model:
    description: "OpenAI model"
    required: false
    default: "gpt-3.5-turbo-16k"
  skip-if-author-is:
    description: "Skip if author is in this list, comma separated"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: skip-if-author-is
      if: ${{ contains(inputs.skip-if-author-is, github.actor) }}
      run: |
        echo "Skipping because author is in skip-if-author-is list"
        echo "Author: ${{ github.actor }}"
        echo "Skip if author is: ${{ inputs.skip-if-author-is }}"
        exit 0
      shell: bash

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: "kieranklaassen/gpt-auto-pr-description-action"
        ref: "main"

    - name: Checkout template file
      uses: actions/checkout@v3
      with:
        sparse-checkout: ${{ inputs.pull-request-template }}
        sparse-checkout-cone-mode: false
        path: "templates"

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install Dependencies
      run: |
        bundle install
      shell: bash

    - id: change-description
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        OPENAI_TOKEN: ${{ inputs.openai-token }}
        REPO: ${{ github.repository }}
        BASE_BRANCH: "main" # update if base branch is not always 'main'
        HEAD_BRANCH: ${{ github.head_ref }} # use github.ref if not in a PR context
        PULL_REQUEST_TEMPLATE: ${{ inputs.pull-request-template }}
        TRIGGER: ${{ inputs.trigger-word }}
        OPENAI_MODEL: ${{ inputs.openai-model }}
      run: bundle exec ruby run.rb
      shell: bash
